version: 0.2

phases:
  install:
    commands:
      - yum update -y -q
    finally:
      - echo install phase is done.
  pre_build:
    commands:
      - npm install --no-progress --silent
    finally:
    - echo pre_build phase is done.
  build:
    commands:
      - npm run-script lint
    finally:
    - echo build phase is done.