service: mailchimp-api-serverless
useDotenv: true

package:
  patterns:
    - '!target/**'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'stg'}
  region: ${opt:region, 'us-west-2'}
  httpApi:
    authorizers:
      serviceAuthorizer:
        # Point request header at which JWT token will be provided
        identitySource: $request.header.Authorization
        # Issuer url, in case of Cognito User Pools url will be like: 
        # https://cognito-idp.${region}.amazonaws.com/${cognitoPoolId}
        issuerUrl: YOUR_COGNITO_ISSUER_URL
        # Audience for which access is intended
        # In case of Cognito User Pools we need to list client ids
        audience:
          - YOUR_COGNITO_APP_CLIENT_ID

functions:
  app:
    handler: app-serverless.handler
    vpc: # Optional VPC. But if you use VPC then both subproperties (securityGroupIds and subnetIds) are required
      securityGroupIds:
        - YOUR_LAMBDA_SECURITY_GROUP
      subnetIds:
        - YOUR_LAMBDA_SUBNET_1
        - YOUR_LAMBDA_SUBNET_2
    timeout: 600
    events:
      - httpApi:
          method: GET
          path: /campaign-report
          authorizer: serviceAuthorizer
      - httpApi:
          method: GET
          path: /campaign-report/summary
          authorizer: serviceAuthorizer
      - sqs: YOUR_SQS_ARN